// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class ArrayOfSMSList {
    protected com.bilionix.sms4b.client.SMSList[] SMSList;
    
    public ArrayOfSMSList() {
    }
    
    public ArrayOfSMSList(com.bilionix.sms4b.client.SMSList[] SMSList) {
        this.SMSList = SMSList;
    }
    
    public com.bilionix.sms4b.client.SMSList[] getSMSList() {
        return SMSList;
    }
    
    public void setSMSList(com.bilionix.sms4b.client.SMSList[] SMSList) {
        this.SMSList = SMSList;
    }
}
