// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.LiteralObjectSerializerBase;
import com.sun.xml.rpc.streaming.XMLReader;
import com.sun.xml.rpc.streaming.XMLReaderUtil;
import com.sun.xml.rpc.streaming.XMLWriter;

import javax.xml.namespace.QName;
import java.util.ArrayList;

public class ArrayOfGroupSMSList_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final QName ns1_GroupSMSList_QNAME = new QName("SMS4B", "GroupSMSList");
    private static final QName ns1_GroupSMSList_TYPE_QNAME = new QName("SMS4B", "GroupSMSList");
    private CombinedSerializer ns1_myGroupSMSList_LiteralSerializer;

    public ArrayOfGroupSMSList_LiteralSerializer(QName type, String encodingStyle) {
        this(type, encodingStyle, false);
    }

    public ArrayOfGroupSMSList_LiteralSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }

    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myGroupSMSList_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.bilionix.sms4b.client.GroupSMSList.class, ns1_GroupSMSList_TYPE_QNAME);
    }

    public Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        com.bilionix.sms4b.client.ArrayOfGroupSMSList instance = new com.bilionix.sms4b.client.ArrayOfGroupSMSList();
        Object member;
        QName elementName;
        java.util.List<Object> values;
        Object value;

        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_GroupSMSList_QNAME))) {
            values = new ArrayList<>();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_GroupSMSList_QNAME))) {
                    value = ns1_myGroupSMSList_LiteralSerializer.deserialize(ns1_GroupSMSList_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new com.bilionix.sms4b.client.GroupSMSList[values.size()];
            member = values.toArray((Object[]) member);
            instance.setGroupSMSList((com.bilionix.sms4b.client.GroupSMSList[])member);
        }
        else {
            instance.setGroupSMSList(new com.bilionix.sms4b.client.GroupSMSList[0]);
        }

        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return instance;
    }

    public void doSerializeAttributes(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.bilionix.sms4b.client.ArrayOfGroupSMSList instance = (com.bilionix.sms4b.client.ArrayOfGroupSMSList)obj;

    }
    public void doSerialize(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.bilionix.sms4b.client.ArrayOfGroupSMSList instance = (com.bilionix.sms4b.client.ArrayOfGroupSMSList)obj;
        
        if (instance.getGroupSMSList() != null) {
            for (int i = 0; i < instance.getGroupSMSList().length; ++i) {
                ns1_myGroupSMSList_LiteralSerializer.serialize(instance.getGroupSMSList()[i], ns1_GroupSMSList_QNAME, null, writer, context);
            }
        }
    }
}
