// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class ArrayOfCheckSMSList {
    protected com.bilionix.sms4b.client.CheckSMSList[] checkSMSList;
    
    public ArrayOfCheckSMSList() {
    }
    
    public ArrayOfCheckSMSList(com.bilionix.sms4b.client.CheckSMSList[] checkSMSList) {
        this.checkSMSList = checkSMSList;
    }
    
    public com.bilionix.sms4b.client.CheckSMSList[] getCheckSMSList() {
        return checkSMSList;
    }
    
    public void setCheckSMSList(com.bilionix.sms4b.client.CheckSMSList[] checkSMSList) {
        this.checkSMSList = checkSMSList;
    }
}
