// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class ArrayOfGroupSMSList {
    protected com.bilionix.sms4b.client.GroupSMSList[] groupSMSList;
    
    public ArrayOfGroupSMSList() {
    }
    
    public ArrayOfGroupSMSList(com.bilionix.sms4b.client.GroupSMSList[] groupSMSList) {
        this.groupSMSList = groupSMSList;
    }
    
    public com.bilionix.sms4b.client.GroupSMSList[] getGroupSMSList() {
        return groupSMSList;
    }
    
    public void setGroupSMSList(com.bilionix.sms4b.client.GroupSMSList[] groupSMSList) {
        this.groupSMSList = groupSMSList;
    }
}
