// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class CancelGroup {
    protected long sessionID;
    protected long group;
    
    public CancelGroup() {
    }
    
    public CancelGroup(long sessionID, long group) {
        this.sessionID = sessionID;
        this.group = group;
    }
    
    public long getSessionID() {
        return sessionID;
    }
    
    public void setSessionID(long sessionID) {
        this.sessionID = sessionID;
    }
    
    public long getGroup() {
        return group;
    }
    
    public void setGroup(long group) {
        this.group = group;
    }
}
