// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class CancelGroupResponse {
    protected int cancelGroupResult;
    
    public CancelGroupResponse() {
    }
    
    public CancelGroupResponse(int cancelGroupResult) {
        this.cancelGroupResult = cancelGroupResult;
    }
    
    public int getCancelGroupResult() {
        return cancelGroupResult;
    }
    
    public void setCancelGroupResult(int cancelGroupResult) {
        this.cancelGroupResult = cancelGroupResult;
    }
}
