// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class CheckSMS {
    protected long sessionId;
    protected com.bilionix.sms4b.client.ArrayOfString guids;
    
    public CheckSMS() {
    }
    
    public CheckSMS(long sessionId, com.bilionix.sms4b.client.ArrayOfString guids) {
        this.sessionId = sessionId;
        this.guids = guids;
    }
    
    public long getSessionId() {
        return sessionId;
    }
    
    public void setSessionId(long sessionId) {
        this.sessionId = sessionId;
    }
    
    public com.bilionix.sms4b.client.ArrayOfString getGuids() {
        return guids;
    }
    
    public void setGuids(com.bilionix.sms4b.client.ArrayOfString guids) {
        this.guids = guids;
    }
}
