// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class CheckSMSResponse {
    protected com.bilionix.sms4b.client.CheckSMSResult checkSMSResult;
    
    public CheckSMSResponse() {
    }
    
    public CheckSMSResponse(com.bilionix.sms4b.client.CheckSMSResult checkSMSResult) {
        this.checkSMSResult = checkSMSResult;
    }
    
    public com.bilionix.sms4b.client.CheckSMSResult getCheckSMSResult() {
        return checkSMSResult;
    }
    
    public void setCheckSMSResult(com.bilionix.sms4b.client.CheckSMSResult checkSMSResult) {
        this.checkSMSResult = checkSMSResult;
    }
}
