// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class CloseSession {
    protected long sessionID;
    
    public CloseSession() {
    }
    
    public CloseSession(long sessionID) {
        this.sessionID = sessionID;
    }
    
    public long getSessionID() {
        return sessionID;
    }
    
    public void setSessionID(long sessionID) {
        this.sessionID = sessionID;
    }
}
