// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class CloseSessionResponse {
    protected int closeSessionResult;
    
    public CloseSessionResponse() {
    }
    
    public CloseSessionResponse(int closeSessionResult) {
        this.closeSessionResult = closeSessionResult;
    }
    
    public int getCloseSessionResult() {
        return closeSessionResult;
    }
    
    public void setCloseSessionResult(int closeSessionResult) {
        this.closeSessionResult = closeSessionResult;
    }
}
