// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class GroupSMSResult {
    protected int result;
    protected long group;
    protected com.bilionix.sms4b.client.ArrayOfCheckSMSList list;
    
    public GroupSMSResult() {
    }
    
    public GroupSMSResult(int result, long group, com.bilionix.sms4b.client.ArrayOfCheckSMSList list) {
        this.result = result;
        this.group = group;
        this.list = list;
    }
    
    public int getResult() {
        return result;
    }
    
    public void setResult(int result) {
        this.result = result;
    }
    
    public long getGroup() {
        return group;
    }
    
    public void setGroup(long group) {
        this.group = group;
    }
    
    public com.bilionix.sms4b.client.ArrayOfCheckSMSList getList() {
        return list;
    }
    
    public void setList(com.bilionix.sms4b.client.ArrayOfCheckSMSList list) {
        this.list = list;
    }
}
