// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class GroupSMS {
    protected long sessionId;
    protected long group;
    protected String source;
    protected int encoding;
    protected String body;
    protected String off;
    protected String start;
    protected String period;
    protected com.bilionix.sms4b.client.ArrayOfGroupSMSList list;

    public GroupSMS() {
    }

    public GroupSMS(long sessionId, long group, String source, int encoding, String body, String off, String start, String period, com.bilionix.sms4b.client.ArrayOfGroupSMSList list) {
        this.sessionId = sessionId;
        this.group = group;
        this.source = source;
        this.encoding = encoding;
        this.body = body;
        this.off = off;
        this.start = start;
        this.period = period;
        this.list = list;
    }

    public long getSessionId() {
        return sessionId;
    }

    public void setSessionId(long sessionId) {
        this.sessionId = sessionId;
    }

    public long getGroup() {
        return group;
    }

    public void setGroup(long group) {
        this.group = group;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public int getEncoding() {
        return encoding;
    }

    public void setEncoding(int encoding) {
        this.encoding = encoding;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getOff() {
        return off;
    }

    public void setOff(String off) {
        this.off = off;
    }

    public String getStart() {
        return start;
    }

    public void setStart(String start) {
        this.start = start;
    }

    public String getPeriod() {
        return period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }
    
    public com.bilionix.sms4b.client.ArrayOfGroupSMSList getList() {
        return list;
    }
    
    public void setList(com.bilionix.sms4b.client.ArrayOfGroupSMSList list) {
        this.list = list;
    }
}
