// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class GroupSMSList {
    protected String g;
    protected String d;
    protected String b;
    protected int e;

    public GroupSMSList() {
    }

    public GroupSMSList(String g, String d, String b, int e) {
        this.g = g;
        this.d = d;
        this.b = b;
        this.e = e;
    }

    public String getG() {
        return g;
    }

    public void setG(String g) {
        this.g = g;
    }

    public String getD() {
        return d;
    }

    public void setD(String d) {
        this.d = d;
    }

    public String getB() {
        return b;
    }

    public void setB(String b) {
        this.b = b;
    }
    
    public int getE() {
        return e;
    }
    
    public void setE(int e) {
        this.e = e;
    }
}
