// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class GroupSMSResponse {
    protected com.bilionix.sms4b.client.GroupSMSResult groupSMSResult;
    
    public GroupSMSResponse() {
    }
    
    public GroupSMSResponse(com.bilionix.sms4b.client.GroupSMSResult groupSMSResult) {
        this.groupSMSResult = groupSMSResult;
    }
    
    public com.bilionix.sms4b.client.GroupSMSResult getGroupSMSResult() {
        return groupSMSResult;
    }
    
    public void setGroupSMSResult(com.bilionix.sms4b.client.GroupSMSResult groupSMSResult) {
        this.groupSMSResult = groupSMSResult;
    }
}
