// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class LoadSMS {
    protected long sessionId;
    protected String changesFrom;
    protected int flags;

    public LoadSMS() {
    }

    public LoadSMS(long sessionId, String changesFrom, int flags) {
        this.sessionId = sessionId;
        this.changesFrom = changesFrom;
        this.flags = flags;
    }

    public long getSessionId() {
        return sessionId;
    }

    public void setSessionId(long sessionId) {
        this.sessionId = sessionId;
    }

    public String getChangesFrom() {
        return changesFrom;
    }

    public void setChangesFrom(String changesFrom) {
        this.changesFrom = changesFrom;
    }
    
    public int getFlags() {
        return flags;
    }
    
    public void setFlags(int flags) {
        this.flags = flags;
    }
}
