// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class LoadSMSResponse {
    protected com.bilionix.sms4b.client.LoadSMSResult loadSMSResult;
    
    public LoadSMSResponse() {
    }
    
    public LoadSMSResponse(com.bilionix.sms4b.client.LoadSMSResult loadSMSResult) {
        this.loadSMSResult = loadSMSResult;
    }
    
    public com.bilionix.sms4b.client.LoadSMSResult getLoadSMSResult() {
        return loadSMSResult;
    }
    
    public void setLoadSMSResult(com.bilionix.sms4b.client.LoadSMSResult loadSMSResult) {
        this.loadSMSResult = loadSMSResult;
    }
}
