// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class ParamSMSResponse {
    protected com.bilionix.sms4b.client.ParamSMSResult paramSMSResult;
    
    public ParamSMSResponse() {
    }
    
    public ParamSMSResponse(com.bilionix.sms4b.client.ParamSMSResult paramSMSResult) {
        this.paramSMSResult = paramSMSResult;
    }
    
    public com.bilionix.sms4b.client.ParamSMSResult getParamSMSResult() {
        return paramSMSResult;
    }
    
    public void setParamSMSResult(com.bilionix.sms4b.client.ParamSMSResult paramSMSResult) {
        this.paramSMSResult = paramSMSResult;
    }
}
