// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class SendSMSResponse {
    protected String sendSMSResult;

    public SendSMSResponse() {
    }

    public SendSMSResponse(String sendSMSResult) {
        this.sendSMSResult = sendSMSResult;
    }

    public String getSendSMSResult() {
        return sendSMSResult;
    }

    public void setSendSMSResult(String sendSMSResult) {
        this.sendSMSResult = sendSMSResult;
    }
}
