// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;


public class StartSessionResponse {
    protected long startSessionResult;
    
    public StartSessionResponse() {
    }
    
    public StartSessionResponse(long startSessionResult) {
        this.startSessionResult = startSessionResult;
    }
    
    public long getStartSessionResult() {
        return startSessionResult;
    }
    
    public void setStartSessionResult(long startSessionResult) {
        this.startSessionResult = startSessionResult;
    }
}
