// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.bilionix.sms4b.client;

import javax.xml.rpc.Service;
import javax.xml.rpc.ServiceException;

public interface WSSM extends Service {
    public com.bilionix.sms4b.client.WSSMSoap getWSSMSoap() throws ServiceException;
}
